import Head from "next/head";
import { Container } from "react-bootstrap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="p-5">
        <h1>Otec Contabilidade</h1>
        <p>
          Qui est sunt nostrud nulla labore nisi culpa occaecat ullamco
          consectetur non. Magna cupidatat in commodo duis. Id nisi exercitation
          et elit aliquip commodo dolor incididunt sint aliqua aliqua proident.
          Pariatur pariatur et amet amet est nulla voluptate aute commodo. Ex do
          sunt officia deserunt ea elit mollit quis non adipisicing. Do laborum
          esse pariatur enim reprehenderit sunt consequat nisi quis Lorem aliqua
          nulla sunt. Nulla aliqua tempor dolore mollit sint dolor enim ex
          cupidatat occaecat exercitation. Nulla aute adipisicing magna nisi ex
          incididunt Lorem laborum. Amet in proident excepteur sit do velit
          adipisicing culpa anim aliquip consectetur. Eu nulla quis nulla irure
          eu veniam.
        </p>
      </Container>
    </div>
  );
}
